CREATE TABLE events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    starts_at TIMESTAMP NOT NULL,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_events_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id),
    CONSTRAINT fk_events_created_by FOREIGN KEY (created_by) REFERENCES users (user_id)
);

CREATE INDEX idx_events_tenant_start ON events (tenant_id, starts_at);

ALTER TABLE attendance ADD COLUMN event_id BIGINT;
ALTER TABLE attendance ADD CONSTRAINT fk_attendance_event FOREIGN KEY (event_id) REFERENCES events (event_id);

CREATE INDEX idx_attendance_event_user ON attendance (event_id, user_id);
