CREATE TABLE tenants (
    tenant_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    tenant_code VARCHAR(255) NOT NULL UNIQUE,
    director VARCHAR(255) NOT NULL,
    member_limit INT NOT NULL,
    status VARCHAR(20) NOT NULL
);

CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    codigo VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    tenant_id BIGINT NOT NULL,
    rol VARCHAR(20) NOT NULL,
    CONSTRAINT fk_users_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id)
);

CREATE INDEX idx_users_tenant ON users (tenant_id);
