CREATE TABLE guests (
    guest_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    tenant_id BIGINT NOT NULL,
    created_by BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_guests_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id),
    CONSTRAINT fk_guests_created_by FOREIGN KEY (created_by) REFERENCES users (user_id),
    CONSTRAINT uq_guests_codigo_tenant UNIQUE (codigo, tenant_id)
);

CREATE INDEX idx_guests_tenant_status ON guests (tenant_id, status);
