CREATE TABLE access_logs (
    access_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_type VARCHAR(20) NOT NULL,
    subject_id BIGINT,
    codigo VARCHAR(255),
    tenant_id BIGINT,
    totp_code VARCHAR(10),
    device_id VARCHAR(255),
    location VARCHAR(255),
    result VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_access_logs_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id)
);

CREATE INDEX idx_access_logs_tenant_created ON access_logs (tenant_id, created_at);
