CREATE TABLE attendance (
    attendance_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    marked_by BIGINT NOT NULL,
    check_in_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_attendance_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id),
    CONSTRAINT fk_attendance_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_attendance_marked_by FOREIGN KEY (marked_by) REFERENCES users (user_id)
);

CREATE INDEX idx_attendance_tenant_date ON attendance (tenant_id, check_in_at);
CREATE INDEX idx_attendance_user_date ON attendance (user_id, check_in_at);
